<?php
return [
    'API_URL' => 'http://2.intel-x.com/api/',

    'Buckets' => [
        'pastes' => 'Pastes',
        'darknet.tor' => 'Darknet: Tor',
        'darknet.i2p' => 'Darknet: I2P',
        'whois' => 'Whois',
        'usenet' => 'Usenet',
        'leaks.private.general' => 'Leaks',
        'leaks.private.comb' => 'Leaks COMB',
        'leaks.logs' => 'Stealer Logs',
        'leaks.public.wikileaks' => 'WikiLeaks',
        'leaks.public.general' => 'Public Leaks',
        'dumpster' => 'Dumpster',
        'documents.public.scihub' => 'Sci-Hub',
    ],

    'PublicWeb' => [
        'web.public.kp' => 'North Korea',
        'web.public.ru' => 'Ukraine',
        'web.public.de' => 'Germany',
        'web.public.com' => '.com',
        'web.public.org' => '.org',
        'web.public.net' => '.net',
        'web.public.info' => '.info',
        'web.public.eu' => '.eu',
        'web.public.cn' => 'China',
        'web.public.nord' => 'Northern Europe',
        'web.public.we' => 'Western Europe',
        'web.public.cee' => 'Central and Eastern Europe',
        'web.public.ams' => 'Americas',
        'web.public.af' => 'Africa',
        'web.public.mea' => 'Middle East and Asia',
        'web.public.oc' => 'Oceania',
        'web.public.tech' => 'Technology',
        'web.public.business' => 'Business',
        'web.public.social' => 'Social',
        'web.public.misc' => 'Misc',
        'web.public.peer' => 'Decentralized TLDs',
        'web.gov.gov' => 'Government US',
        'web.gov.ru' => 'Government Russia',
    ],
];
